Modify homepage with search bar and course options
teamup-org/TeamUp-PeerTutorApp pull request #2
Opened 2024-06-25 01:39 UTC by anhkha2003

- Modify homepage by adding search bar and 6 course options with images
- Allow users to redirect to list of tutors by clicking the respective major in homepage
- Edit route.ts to allow redirecting to pages with GET parameters
- Fix tutor profile schedule bug by replacing useSession with useUser
- Add major parameter to URL of tutor filter to search tutors with major by URL
- Edit the .gitignore of frontend

2024-06-30 21:43 UTC, fornerobj requested changes
tutor-profile-schedule.tsx page useUser() method needs to be fixed as described in the comment

2024-06-30 21:43 UTC, fornerobj commented on frontend/src/app/(ui)/dashboard/tutors/tutor-profile-schedule.tsx
Correct usage for useUser looks like this. No longer need .data?.user? etc
Feel free to check my implementation on other pages such as the dashboard

const { user } = useUser();
const userEmail = user?.email;

2024-06-30 21:43 UTC, fornerobj commented on frontend/src/app/page.tsx
This is a good change. Thank you for fixing my sloppy implementation

2024-07-01 03:22 UTC, anhkha2003 commented on frontend/src/app/(ui)/dashboard/tutors/tutor-profile-schedule.tsx
![image](https://github.com/teamup-org/TeamUp-PeerTutorApp/assets/76896393/782303bb-7dac-4149-a07c-7d5628ab8154)
This is my change. Should it be like this?

2024-07-01 22:43 UTC, merged